// Code generated by capnpc-go. DO NOT EDIT.

package account

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type AccountFactory struct{ Client capnp.Client }

// AccountFactory_TypeID is the unique identifier for the type AccountFactory.
const AccountFactory_TypeID = 0xc61948737160d61d

func (c AccountFactory) CreateAccount(ctx context.Context, params func(AccountFactory_createAccount_Params) error, opts ...capnp.CallOption) AccountFactory_createAccount_Results_Promise {
	if c.Client == nil {
		return AccountFactory_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      0,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "createAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(AccountFactory_createAccount_Params{Struct: s}) }
	}
	return AccountFactory_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c AccountFactory) DeleteAccount(ctx context.Context, params func(AccountFactory_deleteAccount_Params) error, opts ...capnp.CallOption) AccountFactory_deleteAccount_Results_Promise {
	if c.Client == nil {
		return AccountFactory_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      1,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "deleteAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(AccountFactory_deleteAccount_Params{Struct: s}) }
	}
	return AccountFactory_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type AccountFactory_Server interface {
	CreateAccount(AccountFactory_createAccount) error

	DeleteAccount(AccountFactory_deleteAccount) error
}

func AccountFactory_ServerToClient(s AccountFactory_Server) AccountFactory {
	c, _ := s.(server.Closer)
	return AccountFactory{Client: server.New(AccountFactory_Methods(nil, s), c)}
}

func AccountFactory_Methods(methods []server.Method, s AccountFactory_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      0,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "createAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := AccountFactory_createAccount{c, opts, AccountFactory_createAccount_Params{Struct: p}, AccountFactory_createAccount_Results{Struct: r}}
			return s.CreateAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      1,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "deleteAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := AccountFactory_deleteAccount{c, opts, AccountFactory_deleteAccount_Params{Struct: p}, AccountFactory_deleteAccount_Results{Struct: r}}
			return s.DeleteAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	return methods
}

// AccountFactory_createAccount holds the arguments for a server call to AccountFactory.createAccount.
type AccountFactory_createAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  AccountFactory_createAccount_Params
	Results AccountFactory_createAccount_Results
}

// AccountFactory_deleteAccount holds the arguments for a server call to AccountFactory.deleteAccount.
type AccountFactory_deleteAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  AccountFactory_deleteAccount_Params
	Results AccountFactory_deleteAccount_Results
}

type AccountFactory_createAccount_Params struct{ capnp.Struct }

// AccountFactory_createAccount_Params_TypeID is the unique identifier for the type AccountFactory_createAccount_Params.
const AccountFactory_createAccount_Params_TypeID = 0xd0aac970d20e01d3

func NewAccountFactory_createAccount_Params(s *capnp.Segment) (AccountFactory_createAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_createAccount_Params{st}, err
}

func NewRootAccountFactory_createAccount_Params(s *capnp.Segment) (AccountFactory_createAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_createAccount_Params{st}, err
}

func ReadRootAccountFactory_createAccount_Params(msg *capnp.Message) (AccountFactory_createAccount_Params, error) {
	root, err := msg.RootPtr()
	return AccountFactory_createAccount_Params{root.Struct()}, err
}

func (s AccountFactory_createAccount_Params) String() string {
	str, _ := text.Marshal(0xd0aac970d20e01d3, s.Struct)
	return str
}

func (s AccountFactory_createAccount_Params) InitialBalance() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s AccountFactory_createAccount_Params) SetInitialBalance(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// AccountFactory_createAccount_Params_List is a list of AccountFactory_createAccount_Params.
type AccountFactory_createAccount_Params_List struct{ capnp.List }

// NewAccountFactory_createAccount_Params creates a new list of AccountFactory_createAccount_Params.
func NewAccountFactory_createAccount_Params_List(s *capnp.Segment, sz int32) (AccountFactory_createAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return AccountFactory_createAccount_Params_List{l}, err
}

func (s AccountFactory_createAccount_Params_List) At(i int) AccountFactory_createAccount_Params {
	return AccountFactory_createAccount_Params{s.List.Struct(i)}
}

func (s AccountFactory_createAccount_Params_List) Set(i int, v AccountFactory_createAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_createAccount_Params_List) String() string {
	str, _ := text.MarshalList(0xd0aac970d20e01d3, s.List)
	return str
}

// AccountFactory_createAccount_Params_Promise is a wrapper for a AccountFactory_createAccount_Params promised by a client call.
type AccountFactory_createAccount_Params_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_createAccount_Params_Promise) Struct() (AccountFactory_createAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_createAccount_Params{s}, err
}

type AccountFactory_createAccount_Results struct{ capnp.Struct }

// AccountFactory_createAccount_Results_TypeID is the unique identifier for the type AccountFactory_createAccount_Results.
const AccountFactory_createAccount_Results_TypeID = 0x82923c59653c5004

func NewAccountFactory_createAccount_Results(s *capnp.Segment) (AccountFactory_createAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_createAccount_Results{st}, err
}

func NewRootAccountFactory_createAccount_Results(s *capnp.Segment) (AccountFactory_createAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_createAccount_Results{st}, err
}

func ReadRootAccountFactory_createAccount_Results(msg *capnp.Message) (AccountFactory_createAccount_Results, error) {
	root, err := msg.RootPtr()
	return AccountFactory_createAccount_Results{root.Struct()}, err
}

func (s AccountFactory_createAccount_Results) String() string {
	str, _ := text.Marshal(0x82923c59653c5004, s.Struct)
	return str
}

func (s AccountFactory_createAccount_Results) Account() (Account, error) {
	p, err := s.Struct.Ptr(0)
	return Account{Struct: p.Struct()}, err
}

func (s AccountFactory_createAccount_Results) HasAccount() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s AccountFactory_createAccount_Results) SetAccount(v Account) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewAccount sets the account field to a newly
// allocated Account struct, preferring placement in s's segment.
func (s AccountFactory_createAccount_Results) NewAccount() (Account, error) {
	ss, err := NewAccount(s.Struct.Segment())
	if err != nil {
		return Account{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// AccountFactory_createAccount_Results_List is a list of AccountFactory_createAccount_Results.
type AccountFactory_createAccount_Results_List struct{ capnp.List }

// NewAccountFactory_createAccount_Results creates a new list of AccountFactory_createAccount_Results.
func NewAccountFactory_createAccount_Results_List(s *capnp.Segment, sz int32) (AccountFactory_createAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return AccountFactory_createAccount_Results_List{l}, err
}

func (s AccountFactory_createAccount_Results_List) At(i int) AccountFactory_createAccount_Results {
	return AccountFactory_createAccount_Results{s.List.Struct(i)}
}

func (s AccountFactory_createAccount_Results_List) Set(i int, v AccountFactory_createAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_createAccount_Results_List) String() string {
	str, _ := text.MarshalList(0x82923c59653c5004, s.List)
	return str
}

// AccountFactory_createAccount_Results_Promise is a wrapper for a AccountFactory_createAccount_Results promised by a client call.
type AccountFactory_createAccount_Results_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_createAccount_Results_Promise) Struct() (AccountFactory_createAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_createAccount_Results{s}, err
}

func (p AccountFactory_createAccount_Results_Promise) Account() Account_Promise {
	return Account_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type AccountFactory_deleteAccount_Params struct{ capnp.Struct }

// AccountFactory_deleteAccount_Params_TypeID is the unique identifier for the type AccountFactory_deleteAccount_Params.
const AccountFactory_deleteAccount_Params_TypeID = 0x9c23de4a86bef993

func NewAccountFactory_deleteAccount_Params(s *capnp.Segment) (AccountFactory_deleteAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_deleteAccount_Params{st}, err
}

func NewRootAccountFactory_deleteAccount_Params(s *capnp.Segment) (AccountFactory_deleteAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_deleteAccount_Params{st}, err
}

func ReadRootAccountFactory_deleteAccount_Params(msg *capnp.Message) (AccountFactory_deleteAccount_Params, error) {
	root, err := msg.RootPtr()
	return AccountFactory_deleteAccount_Params{root.Struct()}, err
}

func (s AccountFactory_deleteAccount_Params) String() string {
	str, _ := text.Marshal(0x9c23de4a86bef993, s.Struct)
	return str
}

func (s AccountFactory_deleteAccount_Params) SourceAccount() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s AccountFactory_deleteAccount_Params) HasSourceAccount() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s AccountFactory_deleteAccount_Params) SourceAccountBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s AccountFactory_deleteAccount_Params) SetSourceAccount(v string) error {
	return s.Struct.SetText(0, v)
}

// AccountFactory_deleteAccount_Params_List is a list of AccountFactory_deleteAccount_Params.
type AccountFactory_deleteAccount_Params_List struct{ capnp.List }

// NewAccountFactory_deleteAccount_Params creates a new list of AccountFactory_deleteAccount_Params.
func NewAccountFactory_deleteAccount_Params_List(s *capnp.Segment, sz int32) (AccountFactory_deleteAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return AccountFactory_deleteAccount_Params_List{l}, err
}

func (s AccountFactory_deleteAccount_Params_List) At(i int) AccountFactory_deleteAccount_Params {
	return AccountFactory_deleteAccount_Params{s.List.Struct(i)}
}

func (s AccountFactory_deleteAccount_Params_List) Set(i int, v AccountFactory_deleteAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_deleteAccount_Params_List) String() string {
	str, _ := text.MarshalList(0x9c23de4a86bef993, s.List)
	return str
}

// AccountFactory_deleteAccount_Params_Promise is a wrapper for a AccountFactory_deleteAccount_Params promised by a client call.
type AccountFactory_deleteAccount_Params_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_deleteAccount_Params_Promise) Struct() (AccountFactory_deleteAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_deleteAccount_Params{s}, err
}

type AccountFactory_deleteAccount_Results struct{ capnp.Struct }

// AccountFactory_deleteAccount_Results_TypeID is the unique identifier for the type AccountFactory_deleteAccount_Results.
const AccountFactory_deleteAccount_Results_TypeID = 0xaa39b2fa669a0512

func NewAccountFactory_deleteAccount_Results(s *capnp.Segment) (AccountFactory_deleteAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_deleteAccount_Results{st}, err
}

func NewRootAccountFactory_deleteAccount_Results(s *capnp.Segment) (AccountFactory_deleteAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_deleteAccount_Results{st}, err
}

func ReadRootAccountFactory_deleteAccount_Results(msg *capnp.Message) (AccountFactory_deleteAccount_Results, error) {
	root, err := msg.RootPtr()
	return AccountFactory_deleteAccount_Results{root.Struct()}, err
}

func (s AccountFactory_deleteAccount_Results) String() string {
	str, _ := text.Marshal(0xaa39b2fa669a0512, s.Struct)
	return str
}

func (s AccountFactory_deleteAccount_Results) Success() bool {
	return s.Struct.Bit(0)
}

func (s AccountFactory_deleteAccount_Results) SetSuccess(v bool) {
	s.Struct.SetBit(0, v)
}

// AccountFactory_deleteAccount_Results_List is a list of AccountFactory_deleteAccount_Results.
type AccountFactory_deleteAccount_Results_List struct{ capnp.List }

// NewAccountFactory_deleteAccount_Results creates a new list of AccountFactory_deleteAccount_Results.
func NewAccountFactory_deleteAccount_Results_List(s *capnp.Segment, sz int32) (AccountFactory_deleteAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return AccountFactory_deleteAccount_Results_List{l}, err
}

func (s AccountFactory_deleteAccount_Results_List) At(i int) AccountFactory_deleteAccount_Results {
	return AccountFactory_deleteAccount_Results{s.List.Struct(i)}
}

func (s AccountFactory_deleteAccount_Results_List) Set(i int, v AccountFactory_deleteAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_deleteAccount_Results_List) String() string {
	str, _ := text.MarshalList(0xaa39b2fa669a0512, s.List)
	return str
}

// AccountFactory_deleteAccount_Results_Promise is a wrapper for a AccountFactory_deleteAccount_Results promised by a client call.
type AccountFactory_deleteAccount_Results_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_deleteAccount_Results_Promise) Struct() (AccountFactory_deleteAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_deleteAccount_Results{s}, err
}

type Account struct{ capnp.Struct }

// Account_TypeID is the unique identifier for the type Account.
const Account_TypeID = 0x83f3b285e41ce339

func NewAccount(s *capnp.Segment) (Account, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Account{st}, err
}

func NewRootAccount(s *capnp.Segment) (Account, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Account{st}, err
}

func ReadRootAccount(msg *capnp.Message) (Account, error) {
	root, err := msg.RootPtr()
	return Account{root.Struct()}, err
}

func (s Account) String() string {
	str, _ := text.Marshal(0x83f3b285e41ce339, s.Struct)
	return str
}

func (s Account) SourceAccount() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Account) HasSourceAccount() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Account) SourceAccountBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Account) SetSourceAccount(v string) error {
	return s.Struct.SetText(0, v)
}

func (s Account) InitialBalance() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s Account) SetInitialBalance(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// Account_List is a list of Account.
type Account_List struct{ capnp.List }

// NewAccount creates a new list of Account.
func NewAccount_List(s *capnp.Segment, sz int32) (Account_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Account_List{l}, err
}

func (s Account_List) At(i int) Account { return Account{s.List.Struct(i)} }

func (s Account_List) Set(i int, v Account) error { return s.List.SetStruct(i, v.Struct) }

func (s Account_List) String() string {
	str, _ := text.MarshalList(0x83f3b285e41ce339, s.List)
	return str
}

// Account_Promise is a wrapper for a Account promised by a client call.
type Account_Promise struct{ *capnp.Pipeline }

func (p Account_Promise) Struct() (Account, error) {
	s, err := p.Pipeline.Struct()
	return Account{s}, err
}

const schema_9a4e56aa8fe168ad = "x\xda\xa4\x92=h\x14A\x1c\xc5\xdf\x9b\xd9u\x83\\" +
	"4\x9b\x8d\xa0\xe0i\xa1\x01#1\xc9\x11\x9b\xc8\xc1%" +
	")D-\xe4\xc6B\xb0s\\W<8o\xcf\xdd=" +
	"B\xd2\x08J\xb4\x14\xb4\x0bZ\xd8\x1e\xd8\xa4\xb3\xd0R" +
	"\xb0\x10\xfc\x00\xc1F\x10\xb5\xb0\xb6\xd2fd\xees\x0b" +
	"c\x02\xa9\xeef\xf6\xcf\xfb\xfd\xdf\x9b7w\x84\x8b\xa2" +
	"\xe4\xaeH@\x9dp\xf7\x18\xa7Z\x8e\xae\x94\x1f\xdd\x85" +
	"?M\xc0\xa5\x07\xcc?\xe3\xb8\x00\x83\x17\xac\x80f\xe1" +
	"\xdb\xe1\xef\xeb\x9b\xbf\xeeA\x15I\xf3\xfc\xe6\xd7\x87\xed" +
	"\xcb\x177z\x93\x9fy\x92\xc1O\xfb7\xf8\xc1\x15\xd0" +
	"<\xfe\xfd\xea\xfe\x85/\xc7\x9e\xe4\xe5\xce\x8b\xbdVN" +
	"\x0b+7\xeen\xdc\xf8\xb3\xb9\xd0\x86\x9a&\x01\xc7\x0e" +
	"\xac\x8b\x0e\xefig\xa0\xf8\xe9\xea\xed\xf4\xdc\xa1\xd7\xf0" +
	"\x8br\x88\x03\xe7_\x8ak\x0c\xde\x0b\xcbz+\x1e\x04" +
	"\x93\xd2\x03\xccG\xee\xfb\xd0|\xd3~\x97\x97\x1b\x95\x1d" +
	"\xde\xa4\xac\xe0\x94i&q\x16\xa7\xb3\xda\x0b\xc3\xb8\xd5" +
	"\xc8fu\xf7w&\xd4\xcdF\xf3\xccR\xf7tV\x87" +
	"Y\x9c\xac\xce\x84I\xa4\xb3\xa8wy\xfcR\x94\xb6\xea" +
	"\x19S\xe5H\x07p\x08\xf8\xa3\xcb\x80\x1a\x91T\x13\x82" +
	"wzR\x1c\x1bf\x04r\x0c\x1c@\xe5V\xd0\xfd\xf6" +
	"X%\xd5\xc8@z*\xb1/\"\xa9N\x0b\x92\x13\xd6" +
	"\x8d_Z\x03\xd4\x9c\xa4*\x0b\x9a4n%a\xb4\x14" +
	"\xe2h\x17[\x80`\x014\xb5F-\xab\xe9\xfa2*" +
	"\xba\xae\x1baD\x17\x82nn\x8b\x1dY\xbf\x1e\xd5\xa3" +
	"\xa1\xf5\xaaN\xf4\xad\x14\xc8[\xb7\xfb\x15$\xd5\xc1\xff" +
	"\xec\xb2\x0b\xe4vi\xa7\xad0\x8c\xd2\x94\x84 s(" +
	"g;\x94\x17'\xab\xdd\xa8\xdd\\a\xd8/\xbe_J" +
	" \xfc)\x8f\xc3\xf2\xb2_R\xbfh\xbf\x1d\xf0L\xbf" +
	"\x18=\xbf\x8b4\xfd\xe5\x077Ur7e\xfbW\xe2" +
	"k\xb9\xc4\xb7z\xe5\xbf\x01\x00\x00\xff\xff\xcdW\x18l"

func init() {
	schemas.Register(schema_9a4e56aa8fe168ad,
		0x82923c59653c5004,
		0x83f3b285e41ce339,
		0x9c23de4a86bef993,
		0xaa39b2fa669a0512,
		0xc61948737160d61d,
		0xd0aac970d20e01d3)
}
