// Code generated by capnpc-go. DO NOT EDIT.

package account

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type AccountFactory struct{ Client capnp.Client }

// AccountFactory_TypeID is the unique identifier for the type AccountFactory.
const AccountFactory_TypeID = 0xc61948737160d61d

func (c AccountFactory) CreateAccount(ctx context.Context, params func(AccountFactory_createAccount_Params) error, opts ...capnp.CallOption) AccountFactory_createAccount_Results_Promise {
	if c.Client == nil {
		return AccountFactory_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      0,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "createAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(AccountFactory_createAccount_Params{Struct: s}) }
	}
	return AccountFactory_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c AccountFactory) DeleteAccount(ctx context.Context, params func(AccountFactory_deleteAccount_Params) error, opts ...capnp.CallOption) AccountFactory_deleteAccount_Results_Promise {
	if c.Client == nil {
		return AccountFactory_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      1,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "deleteAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(AccountFactory_deleteAccount_Params{Struct: s}) }
	}
	return AccountFactory_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type AccountFactory_Server interface {
	CreateAccount(AccountFactory_createAccount) error

	DeleteAccount(AccountFactory_deleteAccount) error
}

func AccountFactory_ServerToClient(s AccountFactory_Server) AccountFactory {
	c, _ := s.(server.Closer)
	return AccountFactory{Client: server.New(AccountFactory_Methods(nil, s), c)}
}

func AccountFactory_Methods(methods []server.Method, s AccountFactory_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      0,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "createAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := AccountFactory_createAccount{c, opts, AccountFactory_createAccount_Params{Struct: p}, AccountFactory_createAccount_Results{Struct: r}}
			return s.CreateAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc61948737160d61d,
			MethodID:      1,
			InterfaceName: "protos/account/account.capnp:AccountFactory",
			MethodName:    "deleteAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := AccountFactory_deleteAccount{c, opts, AccountFactory_deleteAccount_Params{Struct: p}, AccountFactory_deleteAccount_Results{Struct: r}}
			return s.DeleteAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	return methods
}

// AccountFactory_createAccount holds the arguments for a server call to AccountFactory.createAccount.
type AccountFactory_createAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  AccountFactory_createAccount_Params
	Results AccountFactory_createAccount_Results
}

// AccountFactory_deleteAccount holds the arguments for a server call to AccountFactory.deleteAccount.
type AccountFactory_deleteAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  AccountFactory_deleteAccount_Params
	Results AccountFactory_deleteAccount_Results
}

type AccountFactory_createAccount_Params struct{ capnp.Struct }

// AccountFactory_createAccount_Params_TypeID is the unique identifier for the type AccountFactory_createAccount_Params.
const AccountFactory_createAccount_Params_TypeID = 0xd0aac970d20e01d3

func NewAccountFactory_createAccount_Params(s *capnp.Segment) (AccountFactory_createAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_createAccount_Params{st}, err
}

func NewRootAccountFactory_createAccount_Params(s *capnp.Segment) (AccountFactory_createAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_createAccount_Params{st}, err
}

func ReadRootAccountFactory_createAccount_Params(msg *capnp.Message) (AccountFactory_createAccount_Params, error) {
	root, err := msg.RootPtr()
	return AccountFactory_createAccount_Params{root.Struct()}, err
}

func (s AccountFactory_createAccount_Params) String() string {
	str, _ := text.Marshal(0xd0aac970d20e01d3, s.Struct)
	return str
}

func (s AccountFactory_createAccount_Params) InitialBalance() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s AccountFactory_createAccount_Params) SetInitialBalance(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// AccountFactory_createAccount_Params_List is a list of AccountFactory_createAccount_Params.
type AccountFactory_createAccount_Params_List struct{ capnp.List }

// NewAccountFactory_createAccount_Params creates a new list of AccountFactory_createAccount_Params.
func NewAccountFactory_createAccount_Params_List(s *capnp.Segment, sz int32) (AccountFactory_createAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return AccountFactory_createAccount_Params_List{l}, err
}

func (s AccountFactory_createAccount_Params_List) At(i int) AccountFactory_createAccount_Params {
	return AccountFactory_createAccount_Params{s.List.Struct(i)}
}

func (s AccountFactory_createAccount_Params_List) Set(i int, v AccountFactory_createAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_createAccount_Params_List) String() string {
	str, _ := text.MarshalList(0xd0aac970d20e01d3, s.List)
	return str
}

// AccountFactory_createAccount_Params_Promise is a wrapper for a AccountFactory_createAccount_Params promised by a client call.
type AccountFactory_createAccount_Params_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_createAccount_Params_Promise) Struct() (AccountFactory_createAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_createAccount_Params{s}, err
}

type AccountFactory_createAccount_Results struct{ capnp.Struct }

// AccountFactory_createAccount_Results_TypeID is the unique identifier for the type AccountFactory_createAccount_Results.
const AccountFactory_createAccount_Results_TypeID = 0x82923c59653c5004

func NewAccountFactory_createAccount_Results(s *capnp.Segment) (AccountFactory_createAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_createAccount_Results{st}, err
}

func NewRootAccountFactory_createAccount_Results(s *capnp.Segment) (AccountFactory_createAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_createAccount_Results{st}, err
}

func ReadRootAccountFactory_createAccount_Results(msg *capnp.Message) (AccountFactory_createAccount_Results, error) {
	root, err := msg.RootPtr()
	return AccountFactory_createAccount_Results{root.Struct()}, err
}

func (s AccountFactory_createAccount_Results) String() string {
	str, _ := text.Marshal(0x82923c59653c5004, s.Struct)
	return str
}

func (s AccountFactory_createAccount_Results) Account() (Account, error) {
	p, err := s.Struct.Ptr(0)
	return Account{Struct: p.Struct()}, err
}

func (s AccountFactory_createAccount_Results) HasAccount() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s AccountFactory_createAccount_Results) SetAccount(v Account) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewAccount sets the account field to a newly
// allocated Account struct, preferring placement in s's segment.
func (s AccountFactory_createAccount_Results) NewAccount() (Account, error) {
	ss, err := NewAccount(s.Struct.Segment())
	if err != nil {
		return Account{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// AccountFactory_createAccount_Results_List is a list of AccountFactory_createAccount_Results.
type AccountFactory_createAccount_Results_List struct{ capnp.List }

// NewAccountFactory_createAccount_Results creates a new list of AccountFactory_createAccount_Results.
func NewAccountFactory_createAccount_Results_List(s *capnp.Segment, sz int32) (AccountFactory_createAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return AccountFactory_createAccount_Results_List{l}, err
}

func (s AccountFactory_createAccount_Results_List) At(i int) AccountFactory_createAccount_Results {
	return AccountFactory_createAccount_Results{s.List.Struct(i)}
}

func (s AccountFactory_createAccount_Results_List) Set(i int, v AccountFactory_createAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_createAccount_Results_List) String() string {
	str, _ := text.MarshalList(0x82923c59653c5004, s.List)
	return str
}

// AccountFactory_createAccount_Results_Promise is a wrapper for a AccountFactory_createAccount_Results promised by a client call.
type AccountFactory_createAccount_Results_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_createAccount_Results_Promise) Struct() (AccountFactory_createAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_createAccount_Results{s}, err
}

func (p AccountFactory_createAccount_Results_Promise) Account() Account_Promise {
	return Account_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type AccountFactory_deleteAccount_Params struct{ capnp.Struct }

// AccountFactory_deleteAccount_Params_TypeID is the unique identifier for the type AccountFactory_deleteAccount_Params.
const AccountFactory_deleteAccount_Params_TypeID = 0x9c23de4a86bef993

func NewAccountFactory_deleteAccount_Params(s *capnp.Segment) (AccountFactory_deleteAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_deleteAccount_Params{st}, err
}

func NewRootAccountFactory_deleteAccount_Params(s *capnp.Segment) (AccountFactory_deleteAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountFactory_deleteAccount_Params{st}, err
}

func ReadRootAccountFactory_deleteAccount_Params(msg *capnp.Message) (AccountFactory_deleteAccount_Params, error) {
	root, err := msg.RootPtr()
	return AccountFactory_deleteAccount_Params{root.Struct()}, err
}

func (s AccountFactory_deleteAccount_Params) String() string {
	str, _ := text.Marshal(0x9c23de4a86bef993, s.Struct)
	return str
}

func (s AccountFactory_deleteAccount_Params) AccountNumber() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s AccountFactory_deleteAccount_Params) HasAccountNumber() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s AccountFactory_deleteAccount_Params) AccountNumberBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s AccountFactory_deleteAccount_Params) SetAccountNumber(v string) error {
	return s.Struct.SetText(0, v)
}

// AccountFactory_deleteAccount_Params_List is a list of AccountFactory_deleteAccount_Params.
type AccountFactory_deleteAccount_Params_List struct{ capnp.List }

// NewAccountFactory_deleteAccount_Params creates a new list of AccountFactory_deleteAccount_Params.
func NewAccountFactory_deleteAccount_Params_List(s *capnp.Segment, sz int32) (AccountFactory_deleteAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return AccountFactory_deleteAccount_Params_List{l}, err
}

func (s AccountFactory_deleteAccount_Params_List) At(i int) AccountFactory_deleteAccount_Params {
	return AccountFactory_deleteAccount_Params{s.List.Struct(i)}
}

func (s AccountFactory_deleteAccount_Params_List) Set(i int, v AccountFactory_deleteAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_deleteAccount_Params_List) String() string {
	str, _ := text.MarshalList(0x9c23de4a86bef993, s.List)
	return str
}

// AccountFactory_deleteAccount_Params_Promise is a wrapper for a AccountFactory_deleteAccount_Params promised by a client call.
type AccountFactory_deleteAccount_Params_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_deleteAccount_Params_Promise) Struct() (AccountFactory_deleteAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_deleteAccount_Params{s}, err
}

type AccountFactory_deleteAccount_Results struct{ capnp.Struct }

// AccountFactory_deleteAccount_Results_TypeID is the unique identifier for the type AccountFactory_deleteAccount_Results.
const AccountFactory_deleteAccount_Results_TypeID = 0xaa39b2fa669a0512

func NewAccountFactory_deleteAccount_Results(s *capnp.Segment) (AccountFactory_deleteAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_deleteAccount_Results{st}, err
}

func NewRootAccountFactory_deleteAccount_Results(s *capnp.Segment) (AccountFactory_deleteAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AccountFactory_deleteAccount_Results{st}, err
}

func ReadRootAccountFactory_deleteAccount_Results(msg *capnp.Message) (AccountFactory_deleteAccount_Results, error) {
	root, err := msg.RootPtr()
	return AccountFactory_deleteAccount_Results{root.Struct()}, err
}

func (s AccountFactory_deleteAccount_Results) String() string {
	str, _ := text.Marshal(0xaa39b2fa669a0512, s.Struct)
	return str
}

func (s AccountFactory_deleteAccount_Results) Success() bool {
	return s.Struct.Bit(0)
}

func (s AccountFactory_deleteAccount_Results) SetSuccess(v bool) {
	s.Struct.SetBit(0, v)
}

// AccountFactory_deleteAccount_Results_List is a list of AccountFactory_deleteAccount_Results.
type AccountFactory_deleteAccount_Results_List struct{ capnp.List }

// NewAccountFactory_deleteAccount_Results creates a new list of AccountFactory_deleteAccount_Results.
func NewAccountFactory_deleteAccount_Results_List(s *capnp.Segment, sz int32) (AccountFactory_deleteAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return AccountFactory_deleteAccount_Results_List{l}, err
}

func (s AccountFactory_deleteAccount_Results_List) At(i int) AccountFactory_deleteAccount_Results {
	return AccountFactory_deleteAccount_Results{s.List.Struct(i)}
}

func (s AccountFactory_deleteAccount_Results_List) Set(i int, v AccountFactory_deleteAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s AccountFactory_deleteAccount_Results_List) String() string {
	str, _ := text.MarshalList(0xaa39b2fa669a0512, s.List)
	return str
}

// AccountFactory_deleteAccount_Results_Promise is a wrapper for a AccountFactory_deleteAccount_Results promised by a client call.
type AccountFactory_deleteAccount_Results_Promise struct{ *capnp.Pipeline }

func (p AccountFactory_deleteAccount_Results_Promise) Struct() (AccountFactory_deleteAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return AccountFactory_deleteAccount_Results{s}, err
}

type Account struct{ capnp.Struct }

// Account_TypeID is the unique identifier for the type Account.
const Account_TypeID = 0x83f3b285e41ce339

func NewAccount(s *capnp.Segment) (Account, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Account{st}, err
}

func NewRootAccount(s *capnp.Segment) (Account, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Account{st}, err
}

func ReadRootAccount(msg *capnp.Message) (Account, error) {
	root, err := msg.RootPtr()
	return Account{root.Struct()}, err
}

func (s Account) String() string {
	str, _ := text.Marshal(0x83f3b285e41ce339, s.Struct)
	return str
}

func (s Account) AccountNumber() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Account) HasAccountNumber() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Account) AccountNumberBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Account) SetAccountNumber(v string) error {
	return s.Struct.SetText(0, v)
}

func (s Account) Balance() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s Account) SetBalance(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

// Account_List is a list of Account.
type Account_List struct{ capnp.List }

// NewAccount creates a new list of Account.
func NewAccount_List(s *capnp.Segment, sz int32) (Account_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Account_List{l}, err
}

func (s Account_List) At(i int) Account { return Account{s.List.Struct(i)} }

func (s Account_List) Set(i int, v Account) error { return s.List.SetStruct(i, v.Struct) }

func (s Account_List) String() string {
	str, _ := text.MarshalList(0x83f3b285e41ce339, s.List)
	return str
}

// Account_Promise is a wrapper for a Account promised by a client call.
type Account_Promise struct{ *capnp.Pipeline }

func (p Account_Promise) Struct() (Account, error) {
	s, err := p.Pipeline.Struct()
	return Account{s}, err
}

const schema_9a4e56aa8fe168ad = "x\xda\xa4\x92?h\x14A\x18\xc5\xdf\x9b\xd9u\xa3\x9c" +
	"\x9a\xcdFPp\x09A\x0b#g\xe2\x11\x0b#\x81\x8b" +
	"\x01E,\xc2\x8d\x85`!8\xb7\xaexp\xb9=w" +
	"\xf7\x08\xb1\x09*j)he\xb0\xb1=\xb0I\x97\xc6" +
	"RH!\x88\x82`#\x88ZX[i\xb32\xf7w" +
	"\x05C\x84T\xbb3\xf3\xf1~\xdf\xf7\xbew\xda\xe7\x82" +
	"(\xd9+\x12P'\xec=\x99U\x99\x0f\xaf\xcd?\xbd" +
	"\x0f\xb7H\xc0\xa6\x03\xcc\xbe\xe4\x98\x00\xbdM\x96\xc1l" +
	"\xee\xeb\xd1o\x0f7~>\x80\xf2\xc9\xec\xd5\xed/O" +
	"\xdaW\x97\xd6{\x95\x9fx\x92\xde\x0f\xf3\xeb}\xe7\x0a" +
	"\x98=\xfb\xf5\xfa\xd1\xe5\xcf\xc7^\xe4\xe5.\x88}F" +
	"\xee\xba0rc\xf6\xfa\xad\xdf\x1bsm\xa8\"\x09X" +
	"\xa6\xe0\x9e\xe8\xf0\x9ew\x0a\xfc\x8f7\xee$\x97\x8e\xbc" +
	"\x81\xeb\xcb!\x0e\x9c\xdd\x14Uzo\x85am\x89\xc7" +
	"\xde\xa4t\x80\xec\x03\x0f\xbcon\xb5\xdf\xe5\xe5\xf6\xca" +
	"\x0eoR\x96q*k\xc6Q\x1a%3\xda\x09\x82\xa8" +
	"\xd5Hgt\xf7;\x1d\xe8f\xa3y\xee|\xf7tQ" +
	"\x07i\x14\xafN\x07q\xa8\xd3\xb0wy\xfcJ\x98\xb4" +
	"\xea)\x13eI\x0b\xb0\x08\xb8\xfb\x17\x015\"\xa9\xc6" +
	"\x05\xd7zR\x1c\x1dz\x04r\x14\x1c@\xe5v\xd0\x83" +
	"\xe6X!\xd5\xc8@z*6\x1b\x91Tg\x04\xc9q" +
	"3\x8d[2\xb8\xa2\xa4:+\x98\xf5D\x960\xd1Z" +
	"\xae\x861\x0b\x10,\x80kU]\xd7\x8d \xa4\x0dA" +
	";\x07\xff\xaf\x89o\x86\xf5p8qE\xc7z9\x01" +
	"\xf2\x13\x9b\xb6\x0a\x92\xea\xf0\xf6-\xec\x06\xb9\x93\xc9I" +
	"+\x08\xc2$!!\xc8\x1c\xca\xda\x09\xe5D\xf1j\xd7" +
	"a;\x97\x13\xf6\xf3\xee\x96b\x08w\xca\xe10\xb3\xec" +
	"g\xd3\xf5\xcd\xdb!'\xeb\xe7\x01\x13\x1d\xd9\x05f\xfd" +
	"\xe6\x077\x15r7\x19\xfb\x97\xe3ws\x8e\xd7\x1a\xb5" +
	"\xb4\xa6\xeb\x8b(\xff\xbd\xe5?\x01\x00\x00\xff\xff^\x1b" +
	"\x14j"

func init() {
	schemas.Register(schema_9a4e56aa8fe168ad,
		0x82923c59653c5004,
		0x83f3b285e41ce339,
		0x9c23de4a86bef993,
		0xaa39b2fa669a0512,
		0xc61948737160d61d,
		0xd0aac970d20e01d3)
}
